workflow:

variables:
  NUGET_PACKAGES_DIRECTORY: '.nuget'

cache:
  key: "$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"
  paths:
    - '$SOURCE_CODE_PATH$OBJECTS_DIRECTORY/project.assets.json'
    - '$SOURCE_CODE_PATH$OBJECTS_DIRECTORY/*.csproj.nuget.*'
    - '$NUGET_PACKAGES_DIRECTORY'

image: mcr.microsoft.com/dotnet/sdk:8.0

stages:
  - build
  - deploy

build-library:
  stage: build
  script:
    - dotnet restore --packages $NUGET_PACKAGES_DIRECTORY
    - dotnet build --no-restore -c Release
  artifacts:
    untracked: true

test-library:
  stage: build
  needs:
    - job: build-library
      artifacts: true
  script:
    - dotnet test --no-build --no-restore -c Release

package-library:
  stage: build
  needs:
    - job: test-library
      artifacts: true
  script:
    dotnet pack -c Release --no-build --output nupkg
  artifacts:
    paths:
      - nupkg

generate-docs:
  stage: deploy
  image: nikolaik/python-nodejs:python3.13-nodejs20-slim
  script: |
    npm install -g @techdocs/cli
    pip install "mkdocs-techdocs-core==1.*"
    techdocs-cli generate --verbose --no-docker
    name=$(awk '/metadata/{flag=1} flag && /name:/{print $NF;flag=""}' catalog-info.yaml)
    kind=$(awk '/kind/{flag=1} flag && /kind:/{print $NF;flag=""}' catalog-info.yaml)
    namespace=$(awk '/metadata/{flag=1} flag && /namespace:/{print $NF;flag=""}' catalog-info.yaml)
    echo $namespace/$kind/$name 
    echo $Intropy_Client_Id  
    export AZURE_CLIENT_ID=$Intropy_Client_Id
    export AZURE_CLIENT_SECRET=$Intropy_Client_Secret
    export AZURE_TENANT_ID=$Intropy_Tenant_Id
    techdocs-cli publish --publisher-type azureBlobStorage --azureAccountName igrbackstage01sa --storage-name docs --entity $namespace/$kind/$name

deploy-nuget:
  stage: deploy
  needs:
    - job: package-library
      artifacts: true
  script:
    - echo "Checking contents of nupkg directory before push:"
    - echo "Pushing package to GitLab Group NuGet package feed"
    - dotnet nuget push nupkg/*.nupkg --api-key "${CI_DEPLOY_PASSWORD}" --source "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/nuget/index.json"
    